### ISSUE TITLE
Getting error code...

### ISSUE THREAD

**Issue by rob2ee** [ShilohBeeler/discordRPG#47]
ReqlDriverError: Connection is closed.
    at ReqlDriverError.ReqlError [as constructor] (/home/Mackan/RPGBot/node_modules/rethinkdb/errors.js:23:13)
    at new ReqlDriverError (/home/Mackan/RPGBot/node_modules/rethinkdb/errors.js:68:50)
    at TcpConnection.Connection._start (/home/Mackan/RPGBot/node_modules/rethinkdb/net.js:417:13)
    at /home/Mackan/RPGBot/node_modules/rethinkdb/ast.js:146:29
    at tryCatcher (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:483:31)
    at new Promise (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:71:37)
    at Gt.TermBase.run (/home/Mackan/RPGBot/node_modules/rethinkdb/ast.js:135:12)
    at User.isIgnored (/home/Mackan/RPGBot/src/Classes/User/user.js:614:92)
    at Object.module.exports [as messageCreate] (/home/Mackan/RPGBot/src/Handlers/messageCreate.js:26:7)
    at Client.DRPG.on.e (/home/Mackan/RPGBot/src/main.js:362:13)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at MessageCreateHandler.handle (/home/Mackan/RPGBot/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/home/Mackan/RPGBot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:120:65)
    at WebSocketManager.eventMessage (/home/Mackan/RPGBot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:273:31)

**Comment by usta** [comment]
@rob2ee is still error still exist ? because 4 days ago we also getting same error but now it looks like it fixed. could you reproduce it again now ?
